robomuse_diff:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'chassis_to_left_wheel'
  right_wheel : 'chassis_to_right_wheel'
  publish_rate: 20.0  # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation :  0.518 # robomuse 5 =0.435 # meters
  wheel_radius :  0.0635 # robomuse 5=0.062025 # meters

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1 #0.9655  # default: 1.0
  wheel_radius_multiplier    : 1 #1.0737 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: no_need_tf 

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 50.0 #1.0  # m/s
      has_acceleration_limits: false
      max_acceleration       : 5.0 #0.8  # m/s^2
      has_jerk_limits        : false
 
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 1.7 #1.7  # rad/s
      has_acceleration_limits: false
      max_acceleration       : 1.5  # rad/s^2
      has_jerk_limits        : false
      max_jerk               : 2.5  # rad/s^3

#Publish to TF directly or not
enable_odom_tf: false

#Name of frame to publish odometry in
odom_frame_id: odom

# Publish the velocity command to be executed.
# It is to monitor the effect of limiters on the controller input.
publish_cmd: true
